language: python
python:
  - 3.8
  - 3.9

branches:
  only:
  - master

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - python -m unittest test.test_maybe
  - python -m unittest test.test_result
  - python -m unittest test.test_cont
