language: python
python:
  - 3.8
  - 3.9

branches:
  only:
  - master

env: PATH=./src/:$PATH

install:
  - pip install -r requirements.txt

script:
  - python -m unittest ./test/test_maybe.py
  - python -m unittest ./test/test_result.py
  - python -m unittest ./test/test_cont.py
